name: Notificacion CI

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificacion a ntfy
        run: |
          curl -H "Title: 🚀 Nuevo Push en main" \
               -H "Priority: high" \
               -d "Se subio nuevo codigo al repositorio DevOps ITLA" \
               https://ntfy.sh/devops-itla


